service: hrm-dev

frameworkVersion: '3'

plugins:
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true


provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: "20201221"
  timeout: 30


functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: "ANY /{proxy+}" 
    url:
      cors: true



          
          
